create table "station"(
                          id integer primary key generated by default as identity,
                          station varchar(50) not null
);

INSERT INTO "station" VALUES
                          (1, 'Station1'),
                          (2, 'Station2'),
                          (3, 'Station3'),
                          (4, 'Station4'),
                          (5, 'Station5');

create table "order"(
                        id integer primary key generated by default as identity,
                        user_id integer not null,
                        from_station_id integer not null,
                        to_station_id integer not null,
                        status integer not null,
                        created TIMESTAMP DEFAULT now(),
                        FOREIGN KEY (from_station_id) REFERENCES station(id),
                        FOREIGN KEY (to_station_id) REFERENCES station(id)
)