create table "user"
(
    id integer primary key generated by default as identity,
    nickname varchar(255) unique,
    email varchar(255) unique,
    password varchar(255) unique,
    created TIMESTAMP DEFAULT now()
);

CREATE TABLE "session" (
    id integer primary key generated by default as identity,
    user_id INT NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);
